/*
 * HAL_INTERRUPT_MANAGER.h
 *
 *  Created on: Jul 16, 2026
 *      Author: Moata
 */

#ifndef MCAL_LAYER_INTERRUPT_HAL_INTERRUPT_MANAGER_H_
#define MCAL_LAYER_INTERRUPT_HAL_INTERRUPT_MANAGER_H_

#define TIMER0_INTERRUPT_FEATURE_ENABLE		INTERRUPT_FEATURE_ENABLE
#define TIMER1_INTERRUPT_FEATURE_ENABLE		INTERRUPT_FEATURE_ENABLE
#define TIMER2_INTERRUPT_FEATURE_ENABLE		INTERRUPT_FEATURE_ENABLE


#endif /* MCAL_LAYER_INTERRUPT_HAL_INTERRUPT_MANAGER_H_ */
