/*
 * HAL_INTERRUPT_CFG.h
 *
 *  Created on: Feb 7, 2026
 *      Author: Moata
 */

#ifndef MCAL_LAYER_INTERRUPT_HAL_INTERRUPT_CFG_H_
#define MCAL_LAYER_INTERRUPT_HAL_INTERRUPT_CFG_H_

#include "HAL_INTERRUPT_MANAGER.h"

#define INTERRUPT_FEATURE_ENABLE		1




#endif /* MCAL_LAYER_INTERRUPT_HAL_INTERRUPT_CFG_H_ */
